/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: 06c8e02e7ca4ec163572ee9f6c1db6be)
// Runtime types generated with workerd@1.20260131.0 2025-04-15 
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		IMAGES_BUCKET: R2Bucket;
		AI: Ai;
		R2_PUBLIC_URL: "https://your-r2-domain.example.com";
		GITHUB_TOKEN: string;
		HUGO_REPO: string;
		MEMOS_API_URL: string;
		MEMOS_API_KEY: string;
		GEMINI_API_KEY: string;
		JINA_API_KEY: string;
		PUSH_QUEUE: Queue;
	}
}
interface Env extends Cloudflare.Env {}
